---
- name: Juniper Config Change
  hosts: juniper
  gather_facts: true
  tasks:
    - name: Juniper using NETCONF
      junipernetworks.junos.junos_config:
        lines:
          - "set system domain-name {{ domain_name }}"
