---
- name: Testing 'file' module (become)
  hosts: servers
  become: True
  become_method: sudo
  vars:
    user: ktbyers
    mode: '0700'
  tasks:
    - name: Ensure directory 'WORK' exists
      ansible.builtin.file:
        path: "/home/{{ user }}/WORK/"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "{{ mode }}"

    - name: Ensure directory 'WORK/tmp' exists
      ansible.builtin.file:
        path: "/home/{{ user }}/WORK/tmp"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "{{ mode }}"
