---
- name: Print out variables
  hosts: cisco5
  gather_facts: False
  vars_prompt:
    - name: bgp_asn
      prompt: "Enter BGP AS Number"
      private: yes

  tasks:
    - name: Debug fact
      ansible.builtin.debug:
        msg: "{{ bgp_asn }}" 
