---
- name: IOS Example
  hosts: cisco
  gather_facts: False
  tasks:
    - cisco.ios.ios_facts:
      tags: facts_only

    - ansible.builtin.debug:
        var: ansible_net_model
      tags: facts_only

    - cisco.ios.ios_command:
        commands: show ip int brief
      tags: show_ip
      register: output

    - ansible.builtin.debug:
        var: output
      tags: show_ip

    - ansible.builtin.debug:
        msg: Hello world
      tags:
        - facts_only
        - show_ip
