---
- name: Exercise 1d
  hosts: nxos
  gather_facts: False
  tasks:
    - name: Gather show version output
      cisco.nxos.nxos_command:
        commands:
          - show version
          - show lldp neighbors
      register: show_output

    - name: Print gathered output
      ansible.builtin.debug:
        var: show_output["stdout_lines"][1]
