---
- name: Exercise3
  hosts: arista
  gather_facts: False

  tasks:
    - name: Retrieve the switching table as JSON
      arista.eos.eos_command:
        commands: show mac address-table | json
      register: output

    - name: Retrieve unicast switching table from data structure
      ansible.builtin.set_fact:
        switch_table: "{{ output.stdout[0].unicastTable.tableEntries }}"

    - name: Use map to extract two relevant fields
      ansible.builtin.set_fact:
        mac_list: "{{ switch_table | map(attribute='macAddress') | list }}"
        intf_list: "{{ switch_table | map(attribute='interface') | list }}"

    - name: Create list of lists using zip
      ansible.builtin.set_fact:
        switch_table_list: "{{ mac_list | zip(intf_list) | list }}"

    - name: Convert to a dictionary
      ansible.builtin.set_fact:
        switch_table_dict: "{{ dict(switch_table_list) }}"

    - name: Print data structure to the screen
      ansible.builtin.debug:
        var: switch_table_dict
