---
- name: Exercise4
  hosts: arista

  tasks:
    - name: Retrieve the switching table as JSON
      arista.eos.eos_command:
        commands: show mac address-table | json
      register: output

    - name: Retrieve unicast switching table from data structure
      ansible.builtin.set_fact:
        switch_table: "{{ output.stdout[0].unicastTable.tableEntries }}"

    - ansible.builtin.debug:
        msg: "{{ item }}"
      loop: "{{ switch_table }}"

    - ansible.builtin.set_fact:
        switch_table_list: "{{ switch_table_list | default([]) + [item.macAddress] }}"
      loop: "{{ switch_table }}"

    - ansible.builtin.debug:
        var: switch_table_list
