---
- hosts: local
  tasks:
    - name: Runtime include
      ansible.builtin.include_tasks: common_tasks2.yml
      tags: foo1

#    - name: Import (pre-processed at playbook parsing)
#      ansible.builtin.import_tasks: common_tasks2.yml
#      tags: foo1
