---
- name: IOS Example
  hosts: cisco
  gather_facts: False
  tasks:
    - cisco.ios.ios_command:
        commands: show ip int brief
      register: output

    - ansible.builtin.debug:
        var: output["stdout_lines"][0][1]
