---
- name: IOS Example
  hosts: cisco
  gather_facts: False
  tasks:
    - cisco.ios.ios_facts:

    - ansible.builtin.debug:
        var: ansible_net_model

    - ansible.builtin.debug:
        msg:
          - "{{ ansible_net_serialnum }}"
          - "{{ ansible_net_system }}"
          - "{{ ansible_net_version }}"
