---
- name: Test Assert
  hosts: nxos1
  gather_facts: True
  tasks:
    - ansible.builtin.debug:
        var: ansible_facts

    - name: Test Assert
      ansible.builtin.assert:
        that:
          - True
          - ansible_facts.net_model == "Nexus9000 9000v Chassis"
          - ansible_facts.net_hostname == "nxos1"

    - name: Test debug task
      ansible.builtin.debug:
        msg: After assert task
