---
- name: IOS Example1
  hosts: cisco5
  gather_facts: False
  tasks:
    - name: Global config
      cisco.ios.ios_config:
        lines:
          - ip domain name bogus.com
          - ntp server 130.126.24.24
          - ntp server 152.2.21.1
