---
- name: EOS Example
  gather_facts: False
  hosts: arista5:arista6

  tasks:
    - name: "Show command (list of commands)"
      arista.eos.eos_command:
        commands: 
          - show interfaces
          - show arp
      register: output

    - ansible.builtin.debug:
        var: output
